### ISSUE TITLE
Crash due to Unexpected error: java.lang.NoClassDefFoundError: com/jamieswhiteshirt/reachentityattributes/ReachEntityAttributes

### ISSUE THREAD

**Issue by Duchey101** [TheWinABagel/Zenith#113]
mc version 1.20.1
java version is jdk 17, game wont boot with any other javaw.exe for some god forsaken reason.

current modlist: 
Fabric API, version 0.92.0+1.20.1
fakerlib 0.1.1
indium 1.0.30+mc1.20.4 (works with 1.20.1 without major errors until I added zenith and dependencies, probably unrelated)
sodium 0.5.8+mc1.20.1
zenith 1.05-1.20.1
zenith attributes 0.1.5

reproduction steps:
create new world
crash after initializing spawn area
also happens when loading an already existing world.

log:
https://paste.ee/p/gfPYm (uploaded via multiMC)

**Comment by TheWinABagel** [comment]
Downgrade to fakerlib 0.1.0, I removed ReachEntityAttributes from fakerlib along with some other changes and forgot to release a newer version of Zenith Attributes with it, my bad
